// Code generated by go-swagger; DO NOT EDIT.

// Package restapi 智慧变电站边缘计算平台系统
//
//  智慧变电站边缘计算平台系统API
//  Schemes:
//    http
//  Host: localhost:8080
//  BasePath: /api
//  Version: 1.0.0
//  License: MIT License https://mit-license.org/
//  Contact: <wind.kaisa@gmail.com>
//
//  Consumes:
//    - application/json
//    - application/x-www-form-urlencoded
//
//  Produces:
//    - application/octet-stream
//    - application/json
//
// swagger:meta
package restapi
