// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	v1 "swagger/apiserver/v1"
)

// GetDeviceFieldInfosOKCode is the HTTP code returned for type GetDeviceFieldInfosOK
const GetDeviceFieldInfosOKCode int = 200

/*GetDeviceFieldInfosOK A successful response.

swagger:response getDeviceFieldInfosOK
*/
type GetDeviceFieldInfosOK struct {

	/*
	  In: Body
	*/
	Payload *v1.DeviceFieldInfos `json:"body,omitempty"`
}

// NewGetDeviceFieldInfosOK creates GetDeviceFieldInfosOK with default headers values
func NewGetDeviceFieldInfosOK() *GetDeviceFieldInfosOK {

	return &GetDeviceFieldInfosOK{}
}

// WithPayload adds the payload to the get device field infos o k response
func (o *GetDeviceFieldInfosOK) WithPayload(payload *v1.DeviceFieldInfos) *GetDeviceFieldInfosOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get device field infos o k response
func (o *GetDeviceFieldInfosOK) SetPayload(payload *v1.DeviceFieldInfos) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDeviceFieldInfosOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
