// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	v1 "swagger/apiserver/v1"

	"github.com/go-openapi/runtime/middleware"
)

// SynchronizeDeviceTemplateInfoHandlerFunc turns a function with the right signature into a synchronize device template info handler
type SynchronizeDeviceTemplateInfoHandlerFunc func(SynchronizeDeviceTemplateInfoParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SynchronizeDeviceTemplateInfoHandlerFunc) Handle(params SynchronizeDeviceTemplateInfoParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// SynchronizeDeviceTemplateInfoHandler interface for that can handle valid synchronize device template info params
type SynchronizeDeviceTemplateInfoHandler interface {
	Handle(SynchronizeDeviceTemplateInfoParams, *v1.Principal) middleware.Responder
}

// NewSynchronizeDeviceTemplateInfo creates a new http.Handler for the synchronize device template info operation
func NewSynchronizeDeviceTemplateInfo(ctx *middleware.Context, handler SynchronizeDeviceTemplateInfoHandler) *SynchronizeDeviceTemplateInfo {
	return &SynchronizeDeviceTemplateInfo{Context: ctx, Handler: handler}
}

/*SynchronizeDeviceTemplateInfo swagger:route POST /v1/devices/templates/synchronize template synchronizeDeviceTemplateInfo

同步设备模版信息

同步设备模版信息

*/
type SynchronizeDeviceTemplateInfo struct {
	Context *middleware.Context
	Handler SynchronizeDeviceTemplateInfoHandler
}

func (o *SynchronizeDeviceTemplateInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSynchronizeDeviceTemplateInfoParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
