// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SynchronizeDeviceTemplateInfoOKCode is the HTTP code returned for type SynchronizeDeviceTemplateInfoOK
const SynchronizeDeviceTemplateInfoOKCode int = 200

/*SynchronizeDeviceTemplateInfoOK A successful response.

swagger:response synchronizeDeviceTemplateInfoOK
*/
type SynchronizeDeviceTemplateInfoOK struct {
}

// NewSynchronizeDeviceTemplateInfoOK creates SynchronizeDeviceTemplateInfoOK with default headers values
func NewSynchronizeDeviceTemplateInfoOK() *SynchronizeDeviceTemplateInfoOK {

	return &SynchronizeDeviceTemplateInfoOK{}
}

// WriteResponse to the client
func (o *SynchronizeDeviceTemplateInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
