// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateDeviceFieldInfoOKCode is the HTTP code returned for type UpdateDeviceFieldInfoOK
const UpdateDeviceFieldInfoOKCode int = 200

/*UpdateDeviceFieldInfoOK A successful response.

swagger:response updateDeviceFieldInfoOK
*/
type UpdateDeviceFieldInfoOK struct {
}

// NewUpdateDeviceFieldInfoOK creates UpdateDeviceFieldInfoOK with default headers values
func NewUpdateDeviceFieldInfoOK() *UpdateDeviceFieldInfoOK {

	return &UpdateDeviceFieldInfoOK{}
}

// WriteResponse to the client
func (o *UpdateDeviceFieldInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
