// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateDeviceProfileInfoOKCode is the HTTP code returned for type UpdateDeviceProfileInfoOK
const UpdateDeviceProfileInfoOKCode int = 200

/*UpdateDeviceProfileInfoOK A successful response.

swagger:response updateDeviceProfileInfoOK
*/
type UpdateDeviceProfileInfoOK struct {
}

// NewUpdateDeviceProfileInfoOK creates UpdateDeviceProfileInfoOK with default headers values
func NewUpdateDeviceProfileInfoOK() *UpdateDeviceProfileInfoOK {

	return &UpdateDeviceProfileInfoOK{}
}

// WriteResponse to the client
func (o *UpdateDeviceProfileInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
