// Code generated by go-swagger; DO NOT EDIT.

package dga

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ConfirmEarlyAlarmOKCode is the HTTP code returned for type ConfirmEarlyAlarmOK
const ConfirmEarlyAlarmOKCode int = 200

/*ConfirmEarlyAlarmOK A successful response.

swagger:response confirmEarlyAlarmOK
*/
type ConfirmEarlyAlarmOK struct {
}

// NewConfirmEarlyAlarmOK creates ConfirmEarlyAlarmOK with default headers values
func NewConfirmEarlyAlarmOK() *ConfirmEarlyAlarmOK {

	return &ConfirmEarlyAlarmOK{}
}

// WriteResponse to the client
func (o *ConfirmEarlyAlarmOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
