// Code generated by go-swagger; DO NOT EDIT.

package dga

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	v1 "swagger/apiserver/v1"
)

// GetEarlyAlarmsOKCode is the HTTP code returned for type GetEarlyAlarmsOK
const GetEarlyAlarmsOKCode int = 200

/*GetEarlyAlarmsOK A successful response.

swagger:response getEarlyAlarmsOK
*/
type GetEarlyAlarmsOK struct {

	/*
	  In: Body
	*/
	Payload *v1.EarlyAlarms `json:"body,omitempty"`
}

// NewGetEarlyAlarmsOK creates GetEarlyAlarmsOK with default headers values
func NewGetEarlyAlarmsOK() *GetEarlyAlarmsOK {

	return &GetEarlyAlarmsOK{}
}

// WithPayload adds the payload to the get early alarms o k response
func (o *GetEarlyAlarmsOK) WithPayload(payload *v1.EarlyAlarms) *GetEarlyAlarmsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get early alarms o k response
func (o *GetEarlyAlarmsOK) SetPayload(payload *v1.EarlyAlarms) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEarlyAlarmsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
