// Code generated by go-swagger; DO NOT EDIT.

package dga

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	v1 "swagger/apiserver/v1"

	"github.com/go-openapi/runtime"
)

// GetEarlyHistoryAlarmsOKCode is the HTTP code returned for type GetEarlyHistoryAlarmsOK
const GetEarlyHistoryAlarmsOKCode int = 200

/*GetEarlyHistoryAlarmsOK A successful response.

swagger:response getEarlyHistoryAlarmsOK
*/
type GetEarlyHistoryAlarmsOK struct {

	/*
	  In: Body
	*/
	Payload *v1.EarlyAlarms `json:"body,omitempty"`
}

// NewGetEarlyHistoryAlarmsOK creates GetEarlyHistoryAlarmsOK with default headers values
func NewGetEarlyHistoryAlarmsOK() *GetEarlyHistoryAlarmsOK {

	return &GetEarlyHistoryAlarmsOK{}
}

// WithPayload adds the payload to the get early history alarms o k response
func (o *GetEarlyHistoryAlarmsOK) WithPayload(payload *v1.EarlyAlarms) *GetEarlyHistoryAlarmsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get early history alarms o k response
func (o *GetEarlyHistoryAlarmsOK) SetPayload(payload *v1.EarlyAlarms) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEarlyHistoryAlarmsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
