// Code generated by go-swagger; DO NOT EDIT.

package dga

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	v1 "swagger/apiserver/v1"
)

// GetEarlyAlarmConfigOKCode is the HTTP code returned for type GetEarlyAlarmConfigOK
const GetEarlyAlarmConfigOKCode int = 200

/*GetEarlyAlarmConfigOK A successful response.

swagger:response getEarlyAlarmConfigOK
*/
type GetEarlyAlarmConfigOK struct {

	/*
	  In: Body
	*/
	Payload *v1.EarlyAlarmConfig `json:"body,omitempty"`
}

// NewGetEarlyAlarmConfigOK creates GetEarlyAlarmConfigOK with default headers values
func NewGetEarlyAlarmConfigOK() *GetEarlyAlarmConfigOK {

	return &GetEarlyAlarmConfigOK{}
}

// WithPayload adds the payload to the get early alarm config o k response
func (o *GetEarlyAlarmConfigOK) WithPayload(payload *v1.EarlyAlarmConfig) *GetEarlyAlarmConfigOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get early alarm config o k response
func (o *GetEarlyAlarmConfigOK) SetPayload(payload *v1.EarlyAlarmConfig) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEarlyAlarmConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
