// Code generated by go-swagger; DO NOT EDIT.

package dga

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ModifyEarlyAlarmConfigOKCode is the HTTP code returned for type ModifyEarlyAlarmConfigOK
const ModifyEarlyAlarmConfigOKCode int = 200

/*ModifyEarlyAlarmConfigOK A successful response.

swagger:response modifyEarlyAlarmConfigOK
*/
type ModifyEarlyAlarmConfigOK struct {
}

// NewModifyEarlyAlarmConfigOK creates ModifyEarlyAlarmConfigOK with default headers values
func NewModifyEarlyAlarmConfigOK() *ModifyEarlyAlarmConfigOK {

	return &ModifyEarlyAlarmConfigOK{}
}

// WriteResponse to the client
func (o *ModifyEarlyAlarmConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
