// Code generated by go-swagger; DO NOT EDIT.

package dga

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	v1 "swagger/apiserver/v1"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateEarlyAlarmConfigHandlerFunc turns a function with the right signature into a update early alarm config handler
type UpdateEarlyAlarmConfigHandlerFunc func(UpdateEarlyAlarmConfigParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateEarlyAlarmConfigHandlerFunc) Handle(params UpdateEarlyAlarmConfigParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateEarlyAlarmConfigHandler interface for that can handle valid update early alarm config params
type UpdateEarlyAlarmConfigHandler interface {
	Handle(UpdateEarlyAlarmConfigParams, *v1.Principal) middleware.Responder
}

// NewUpdateEarlyAlarmConfig creates a new http.Handler for the update early alarm config operation
func NewUpdateEarlyAlarmConfig(ctx *middleware.Context, handler UpdateEarlyAlarmConfigHandler) *UpdateEarlyAlarmConfig {
	return &UpdateEarlyAlarmConfig{Context: ctx, Handler: handler}
}

/*UpdateEarlyAlarmConfig swagger:route PUT /v1/dga/early/config dga updateEarlyAlarmConfig

修改油中溶解预警配置

修改油中溶解预警配置

*/
type UpdateEarlyAlarmConfig struct {
	Context *middleware.Context
	Handler UpdateEarlyAlarmConfigHandler
}

func (o *UpdateEarlyAlarmConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateEarlyAlarmConfigParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
