// Code generated by go-swagger; DO NOT EDIT.

package dga

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateEarlyAlarmConfigOKCode is the HTTP code returned for type UpdateEarlyAlarmConfigOK
const UpdateEarlyAlarmConfigOKCode int = 200

/*UpdateEarlyAlarmConfigOK A successful response.

swagger:response updateEarlyAlarmConfigOK
*/
type UpdateEarlyAlarmConfigOK struct {
}

// NewUpdateEarlyAlarmConfigOK creates UpdateEarlyAlarmConfigOK with default headers values
func NewUpdateEarlyAlarmConfigOK() *UpdateEarlyAlarmConfigOK {

	return &UpdateEarlyAlarmConfigOK{}
}

// WriteResponse to the client
func (o *UpdateEarlyAlarmConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
