// Code generated by go-swagger; DO NOT EDIT.

package alarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ConfirmIntelligenceAlarmOKCode is the HTTP code returned for type ConfirmIntelligenceAlarmOK
const ConfirmIntelligenceAlarmOKCode int = 200

/*ConfirmIntelligenceAlarmOK A successful response.

swagger:response confirmIntelligenceAlarmOK
*/
type ConfirmIntelligenceAlarmOK struct {
}

// NewConfirmIntelligenceAlarmOK creates ConfirmIntelligenceAlarmOK with default headers values
func NewConfirmIntelligenceAlarmOK() *ConfirmIntelligenceAlarmOK {

	return &ConfirmIntelligenceAlarmOK{}
}

// WriteResponse to the client
func (o *ConfirmIntelligenceAlarmOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
