// Code generated by go-swagger; DO NOT EDIT.

package alarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetLimitAlarmConfigHandlerFunc turns a function with the right signature into a get limit alarm config handler
type GetLimitAlarmConfigHandlerFunc func(GetLimitAlarmConfigParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetLimitAlarmConfigHandlerFunc) Handle(params GetLimitAlarmConfigParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetLimitAlarmConfigHandler interface for that can handle valid get limit alarm config params
type GetLimitAlarmConfigHandler interface {
	Handle(GetLimitAlarmConfigParams, interface{}) middleware.Responder
}

// NewGetLimitAlarmConfig creates a new http.Handler for the get limit alarm config operation
func NewGetLimitAlarmConfig(ctx *middleware.Context, handler GetLimitAlarmConfigHandler) *GetLimitAlarmConfig {
	return &GetLimitAlarmConfig{Context: ctx, Handler: handler}
}

/*GetLimitAlarmConfig swagger:route GET /v1/alarms/limit/config alarm getLimitAlarmConfig

获取超限告警配置

获取超限告警配置

*/
type GetLimitAlarmConfig struct {
	Context *middleware.Context
	Handler GetLimitAlarmConfigHandler
}

func (o *GetLimitAlarmConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetLimitAlarmConfigParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
