// Code generated by go-swagger; DO NOT EDIT.

package alarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetLimitAlarmConfigParams creates a new GetLimitAlarmConfigParams object
// no default values defined in spec.
func NewGetLimitAlarmConfigParams() GetLimitAlarmConfigParams {

	return GetLimitAlarmConfigParams{}
}

// GetLimitAlarmConfigParams contains all the bound params for the get limit alarm config operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetLimitAlarmConfig
type GetLimitAlarmConfigParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*设备类型
	  In: query
	*/
	DeviceName *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetLimitAlarmConfigParams() beforehand.
func (o *GetLimitAlarmConfigParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qDeviceName, qhkDeviceName, _ := qs.GetOK("deviceName")
	if err := o.bindDeviceName(qDeviceName, qhkDeviceName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDeviceName binds and validates parameter DeviceName from query.
func (o *GetLimitAlarmConfigParams) bindDeviceName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.DeviceName = &raw

	return nil
}
