// Code generated by go-swagger; DO NOT EDIT.

package alarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	v1 "swagger/apiserver/v1"

	"github.com/go-openapi/runtime/middleware"
)

// GetLimitAlarmsHandlerFunc turns a function with the right signature into a get limit alarms handler
type GetLimitAlarmsHandlerFunc func(GetLimitAlarmsParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetLimitAlarmsHandlerFunc) Handle(params GetLimitAlarmsParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetLimitAlarmsHandler interface for that can handle valid get limit alarms params
type GetLimitAlarmsHandler interface {
	Handle(GetLimitAlarmsParams, *v1.Principal) middleware.Responder
}

// NewGetLimitAlarms creates a new http.Handler for the get limit alarms operation
func NewGetLimitAlarms(ctx *middleware.Context, handler GetLimitAlarmsHandler) *GetLimitAlarms {
	return &GetLimitAlarms{Context: ctx, Handler: handler}
}

/*GetLimitAlarms swagger:route GET /v1/alarms/limit alarm getLimitAlarms

获取超限告警列表

获取超限告警列表

*/
type GetLimitAlarms struct {
	Context *middleware.Context
	Handler GetLimitAlarmsHandler
}

func (o *GetLimitAlarms) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetLimitAlarmsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
