// Code generated by go-swagger; DO NOT EDIT.

package alarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	v1 "swagger/apiserver/v1"

	"github.com/go-openapi/runtime"
)

// GetHistoryTransferAlarmsOKCode is the HTTP code returned for type GetHistoryTransferAlarmsOK
const GetHistoryTransferAlarmsOKCode int = 200

/*GetHistoryTransferAlarmsOK A successful response.

swagger:response getHistoryTransferAlarmsOK
*/
type GetHistoryTransferAlarmsOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Alarms `json:"body,omitempty"`
}

// NewGetHistoryTransferAlarmsOK creates GetHistoryTransferAlarmsOK with default headers values
func NewGetHistoryTransferAlarmsOK() *GetHistoryTransferAlarmsOK {

	return &GetHistoryTransferAlarmsOK{}
}

// WithPayload adds the payload to the get history transfer alarms o k response
func (o *GetHistoryTransferAlarmsOK) WithPayload(payload *v1.Alarms) *GetHistoryTransferAlarmsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get history transfer alarms o k response
func (o *GetHistoryTransferAlarmsOK) SetPayload(payload *v1.Alarms) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHistoryTransferAlarmsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
