// Code generated by go-swagger; DO NOT EDIT.

package alarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	v1 "swagger/apiserver/v1"
)

// GetDeviceAlarmsOKCode is the HTTP code returned for type GetDeviceAlarmsOK
const GetDeviceAlarmsOKCode int = 200

/*GetDeviceAlarmsOK A successful response.

swagger:response getDeviceAlarmsOK
*/
type GetDeviceAlarmsOK struct {

	/*
	  In: Body
	*/
	Payload *v1.DeviceAlarms `json:"body,omitempty"`
}

// NewGetDeviceAlarmsOK creates GetDeviceAlarmsOK with default headers values
func NewGetDeviceAlarmsOK() *GetDeviceAlarmsOK {

	return &GetDeviceAlarmsOK{}
}

// WithPayload adds the payload to the get device alarms o k response
func (o *GetDeviceAlarmsOK) WithPayload(payload *v1.DeviceAlarms) *GetDeviceAlarmsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get device alarms o k response
func (o *GetDeviceAlarmsOK) SetPayload(payload *v1.DeviceAlarms) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDeviceAlarmsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
