// Code generated by go-swagger; DO NOT EDIT.

package alarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	v1 "swagger/apiserver/v1"

	"github.com/go-openapi/runtime/middleware"
)

// GetHistoryTransferAlarmsHandlerFunc turns a function with the right signature into a get history transfer alarms handler
type GetHistoryTransferAlarmsHandlerFunc func(GetHistoryTransferAlarmsParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetHistoryTransferAlarmsHandlerFunc) Handle(params GetHistoryTransferAlarmsParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetHistoryTransferAlarmsHandler interface for that can handle valid get history transfer alarms params
type GetHistoryTransferAlarmsHandler interface {
	Handle(GetHistoryTransferAlarmsParams, *v1.Principal) middleware.Responder
}

// NewGetHistoryTransferAlarms creates a new http.Handler for the get history transfer alarms operation
func NewGetHistoryTransferAlarms(ctx *middleware.Context, handler GetHistoryTransferAlarmsHandler) *GetHistoryTransferAlarms {
	return &GetHistoryTransferAlarms{Context: ctx, Handler: handler}
}

/*GetHistoryTransferAlarms swagger:route GET /v1/alarms/transfer/history alarm getHistoryTransferAlarms

获取历史传输告警列表

获取历史传输告警列表

*/
type GetHistoryTransferAlarms struct {
	Context *middleware.Context
	Handler GetHistoryTransferAlarmsHandler
}

func (o *GetHistoryTransferAlarms) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetHistoryTransferAlarmsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
