// Code generated by go-swagger; DO NOT EDIT.

package alarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	v1 "swagger/apiserver/v1"

	"github.com/go-openapi/runtime"
)

// GetLimitAlarmsOKCode is the HTTP code returned for type GetLimitAlarmsOK
const GetLimitAlarmsOKCode int = 200

/*GetLimitAlarmsOK A successful response.

swagger:response getLimitAlarmsOK
*/
type GetLimitAlarmsOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Alarms `json:"body,omitempty"`
}

// NewGetLimitAlarmsOK creates GetLimitAlarmsOK with default headers values
func NewGetLimitAlarmsOK() *GetLimitAlarmsOK {

	return &GetLimitAlarmsOK{}
}

// WithPayload adds the payload to the get limit alarms o k response
func (o *GetLimitAlarmsOK) WithPayload(payload *v1.Alarms) *GetLimitAlarmsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get limit alarms o k response
func (o *GetLimitAlarmsOK) SetPayload(payload *v1.Alarms) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLimitAlarmsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
