// Code generated by go-swagger; DO NOT EDIT.

package alarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	v1 "swagger/apiserver/v1"

	"github.com/go-openapi/runtime"
)

// GetTransferAlarmsOKCode is the HTTP code returned for type GetTransferAlarmsOK
const GetTransferAlarmsOKCode int = 200

/*GetTransferAlarmsOK A successful response.

swagger:response getTransferAlarmsOK
*/
type GetTransferAlarmsOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Alarms `json:"body,omitempty"`
}

// NewGetTransferAlarmsOK creates GetTransferAlarmsOK with default headers values
func NewGetTransferAlarmsOK() *GetTransferAlarmsOK {

	return &GetTransferAlarmsOK{}
}

// WithPayload adds the payload to the get transfer alarms o k response
func (o *GetTransferAlarmsOK) WithPayload(payload *v1.Alarms) *GetTransferAlarmsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get transfer alarms o k response
func (o *GetTransferAlarmsOK) SetPayload(payload *v1.Alarms) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTransferAlarmsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
