// Code generated by go-swagger; DO NOT EDIT.

package alarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ModifyLimitAlarmConfigOKCode is the HTTP code returned for type ModifyLimitAlarmConfigOK
const ModifyLimitAlarmConfigOKCode int = 200

/*ModifyLimitAlarmConfigOK A successful response.

swagger:response modifyLimitAlarmConfigOK
*/
type ModifyLimitAlarmConfigOK struct {
}

// NewModifyLimitAlarmConfigOK creates ModifyLimitAlarmConfigOK with default headers values
func NewModifyLimitAlarmConfigOK() *ModifyLimitAlarmConfigOK {

	return &ModifyLimitAlarmConfigOK{}
}

// WriteResponse to the client
func (o *ModifyLimitAlarmConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
