// Code generated by go-swagger; DO NOT EDIT.

package alarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateLimitAlarmConfigOKCode is the HTTP code returned for type UpdateLimitAlarmConfigOK
const UpdateLimitAlarmConfigOKCode int = 200

/*UpdateLimitAlarmConfigOK A successful response.

swagger:response updateLimitAlarmConfigOK
*/
type UpdateLimitAlarmConfigOK struct {
}

// NewUpdateLimitAlarmConfigOK creates UpdateLimitAlarmConfigOK with default headers values
func NewUpdateLimitAlarmConfigOK() *UpdateLimitAlarmConfigOK {

	return &UpdateLimitAlarmConfigOK{}
}

// WriteResponse to the client
func (o *UpdateLimitAlarmConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
