// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ConfigOKCode is the HTTP code returned for type ConfigOK
const ConfigOKCode int = 200

/*ConfigOK A successful response.

swagger:response configOK
*/
type ConfigOK struct {
}

// NewConfigOK creates ConfigOK with default headers values
func NewConfigOK() *ConfigOK {

	return &ConfigOK{}
}

// WriteResponse to the client
func (o *ConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
