// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ControlAlarmTaskOKCode is the HTTP code returned for type ControlAlarmTaskOK
const ControlAlarmTaskOKCode int = 200

/*ControlAlarmTaskOK A successful response.

swagger:response controlAlarmTaskOK
*/
type ControlAlarmTaskOK struct {
}

// NewControlAlarmTaskOK creates ControlAlarmTaskOK with default headers values
func NewControlAlarmTaskOK() *ControlAlarmTaskOK {

	return &ControlAlarmTaskOK{}
}

// WriteResponse to the client
func (o *ControlAlarmTaskOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
