// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateCleaningConfigsOKCode is the HTTP code returned for type CreateCleaningConfigsOK
const CreateCleaningConfigsOKCode int = 200

/*CreateCleaningConfigsOK A successful response.

swagger:response createCleaningConfigsOK
*/
type CreateCleaningConfigsOK struct {
}

// NewCreateCleaningConfigsOK creates CreateCleaningConfigsOK with default headers values
func NewCreateCleaningConfigsOK() *CreateCleaningConfigsOK {

	return &CreateCleaningConfigsOK{}
}

// WriteResponse to the client
func (o *CreateCleaningConfigsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
