// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteCleaningConfigsOKCode is the HTTP code returned for type DeleteCleaningConfigsOK
const DeleteCleaningConfigsOKCode int = 200

/*DeleteCleaningConfigsOK A successful response.

swagger:response deleteCleaningConfigsOK
*/
type DeleteCleaningConfigsOK struct {
}

// NewDeleteCleaningConfigsOK creates DeleteCleaningConfigsOK with default headers values
func NewDeleteCleaningConfigsOK() *DeleteCleaningConfigsOK {

	return &DeleteCleaningConfigsOK{}
}

// WriteResponse to the client
func (o *DeleteCleaningConfigsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
