// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	v1 "swagger/apiserver/v1"

	"github.com/go-openapi/runtime/middleware"
)

// GetTransferAlarmConfigHandlerFunc turns a function with the right signature into a get transfer alarm config handler
type GetTransferAlarmConfigHandlerFunc func(GetTransferAlarmConfigParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTransferAlarmConfigHandlerFunc) Handle(params GetTransferAlarmConfigParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetTransferAlarmConfigHandler interface for that can handle valid get transfer alarm config params
type GetTransferAlarmConfigHandler interface {
	Handle(GetTransferAlarmConfigParams, *v1.Principal) middleware.Responder
}

// NewGetTransferAlarmConfig creates a new http.Handler for the get transfer alarm config operation
func NewGetTransferAlarmConfig(ctx *middleware.Context, handler GetTransferAlarmConfigHandler) *GetTransferAlarmConfig {
	return &GetTransferAlarmConfig{Context: ctx, Handler: handler}
}

/*GetTransferAlarmConfig swagger:route GET /v1/configs/alarms/transfer config getTransferAlarmConfig

获取传输告警配置信息

获取传输告警配置信息

*/
type GetTransferAlarmConfig struct {
	Context *middleware.Context
	Handler GetTransferAlarmConfigHandler
}

func (o *GetTransferAlarmConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTransferAlarmConfigParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
