// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	v1 "swagger/apiserver/v1"

	"github.com/go-openapi/runtime/middleware"
)

// GetAlarmConfigsHandlerFunc turns a function with the right signature into a get alarm configs handler
type GetAlarmConfigsHandlerFunc func(GetAlarmConfigsParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAlarmConfigsHandlerFunc) Handle(params GetAlarmConfigsParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetAlarmConfigsHandler interface for that can handle valid get alarm configs params
type GetAlarmConfigsHandler interface {
	Handle(GetAlarmConfigsParams, *v1.Principal) middleware.Responder
}

// NewGetAlarmConfigs creates a new http.Handler for the get alarm configs operation
func NewGetAlarmConfigs(ctx *middleware.Context, handler GetAlarmConfigsHandler) *GetAlarmConfigs {
	return &GetAlarmConfigs{Context: ctx, Handler: handler}
}

/*GetAlarmConfigs swagger:route GET /v1/configs/alarms config getAlarmConfigs

获取解析告警配置信息

获取解析告警配置信息

*/
type GetAlarmConfigs struct {
	Context *middleware.Context
	Handler GetAlarmConfigsHandler
}

func (o *GetAlarmConfigs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAlarmConfigsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
