// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	v1 "swagger/apiserver/v1"
)

// GetAlarmConfigsOKCode is the HTTP code returned for type GetAlarmConfigsOK
const GetAlarmConfigsOKCode int = 200

/*GetAlarmConfigsOK A successful response.

swagger:response getAlarmConfigsOK
*/
type GetAlarmConfigsOK struct {

	/*
	  In: Body
	*/
	Payload *v1.AlarmConfigs `json:"body,omitempty"`
}

// NewGetAlarmConfigsOK creates GetAlarmConfigsOK with default headers values
func NewGetAlarmConfigsOK() *GetAlarmConfigsOK {

	return &GetAlarmConfigsOK{}
}

// WithPayload adds the payload to the get alarm configs o k response
func (o *GetAlarmConfigsOK) WithPayload(payload *v1.AlarmConfigs) *GetAlarmConfigsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get alarm configs o k response
func (o *GetAlarmConfigsOK) SetPayload(payload *v1.AlarmConfigs) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAlarmConfigsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
