// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	v1 "swagger/apiserver/v1"
)

// GetCleaningConfigsOKCode is the HTTP code returned for type GetCleaningConfigsOK
const GetCleaningConfigsOKCode int = 200

/*GetCleaningConfigsOK A successful response.

swagger:response getCleaningConfigsOK
*/
type GetCleaningConfigsOK struct {

	/*
	  In: Body
	*/
	Payload *v1.CleaningConfigs `json:"body,omitempty"`
}

// NewGetCleaningConfigsOK creates GetCleaningConfigsOK with default headers values
func NewGetCleaningConfigsOK() *GetCleaningConfigsOK {

	return &GetCleaningConfigsOK{}
}

// WithPayload adds the payload to the get cleaning configs o k response
func (o *GetCleaningConfigsOK) WithPayload(payload *v1.CleaningConfigs) *GetCleaningConfigsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cleaning configs o k response
func (o *GetCleaningConfigsOK) SetPayload(payload *v1.CleaningConfigs) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCleaningConfigsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
