// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	v1 "swagger/apiserver/v1"
)

// GetTransferAlarmConfigOKCode is the HTTP code returned for type GetTransferAlarmConfigOK
const GetTransferAlarmConfigOKCode int = 200

/*GetTransferAlarmConfigOK A successful response.

swagger:response getTransferAlarmConfigOK
*/
type GetTransferAlarmConfigOK struct {

	/*
	  In: Body
	*/
	Payload *v1.TransferAlarmConfig `json:"body,omitempty"`
}

// NewGetTransferAlarmConfigOK creates GetTransferAlarmConfigOK with default headers values
func NewGetTransferAlarmConfigOK() *GetTransferAlarmConfigOK {

	return &GetTransferAlarmConfigOK{}
}

// WithPayload adds the payload to the get transfer alarm config o k response
func (o *GetTransferAlarmConfigOK) WithPayload(payload *v1.TransferAlarmConfig) *GetTransferAlarmConfigOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get transfer alarm config o k response
func (o *GetTransferAlarmConfigOK) SetPayload(payload *v1.TransferAlarmConfig) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTransferAlarmConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
