// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ModifyTransferAlarmConfigHandlerFunc turns a function with the right signature into a modify transfer alarm config handler
type ModifyTransferAlarmConfigHandlerFunc func(ModifyTransferAlarmConfigParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ModifyTransferAlarmConfigHandlerFunc) Handle(params ModifyTransferAlarmConfigParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ModifyTransferAlarmConfigHandler interface for that can handle valid modify transfer alarm config params
type ModifyTransferAlarmConfigHandler interface {
	Handle(ModifyTransferAlarmConfigParams, interface{}) middleware.Responder
}

// NewModifyTransferAlarmConfig creates a new http.Handler for the modify transfer alarm config operation
func NewModifyTransferAlarmConfig(ctx *middleware.Context, handler ModifyTransferAlarmConfigHandler) *ModifyTransferAlarmConfig {
	return &ModifyTransferAlarmConfig{Context: ctx, Handler: handler}
}

/*ModifyTransferAlarmConfig swagger:route PUT /v1/configs/alarms/transfer/field config modifyTransferAlarmConfig

修改传输告警属性配置信息

修改传输告警属性配置信息

*/
type ModifyTransferAlarmConfig struct {
	Context *middleware.Context
	Handler ModifyTransferAlarmConfigHandler
}

func (o *ModifyTransferAlarmConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewModifyTransferAlarmConfigParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
