// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateTransferAlarmConfigOKCode is the HTTP code returned for type UpdateTransferAlarmConfigOK
const UpdateTransferAlarmConfigOKCode int = 200

/*UpdateTransferAlarmConfigOK A successful response.

swagger:response updateTransferAlarmConfigOK
*/
type UpdateTransferAlarmConfigOK struct {
}

// NewUpdateTransferAlarmConfigOK creates UpdateTransferAlarmConfigOK with default headers values
func NewUpdateTransferAlarmConfigOK() *UpdateTransferAlarmConfigOK {

	return &UpdateTransferAlarmConfigOK{}
}

// WriteResponse to the client
func (o *UpdateTransferAlarmConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
