// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateCleaningConfigsOKCode is the HTTP code returned for type UpdateCleaningConfigsOK
const UpdateCleaningConfigsOKCode int = 200

/*UpdateCleaningConfigsOK A successful response.

swagger:response updateCleaningConfigsOK
*/
type UpdateCleaningConfigsOK struct {
}

// NewUpdateCleaningConfigsOK creates UpdateCleaningConfigsOK with default headers values
func NewUpdateCleaningConfigsOK() *UpdateCleaningConfigsOK {

	return &UpdateCleaningConfigsOK{}
}

// WriteResponse to the client
func (o *UpdateCleaningConfigsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
