// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewChangeCurrentUserPasswordParams creates a new ChangeCurrentUserPasswordParams object
// no default values defined in spec.
func NewChangeCurrentUserPasswordParams() ChangeCurrentUserPasswordParams {

	return ChangeCurrentUserPasswordParams{}
}

// ChangeCurrentUserPasswordParams contains all the bound params for the change current user password operation
// typically these are obtained from a http.Request
//
// swagger:parameters ChangeCurrentUserPassword
type ChangeCurrentUserPasswordParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*新密码
	  Required: true
	  In: formData
	*/
	NewPassword string
	/*原始密码
	  Required: true
	  In: formData
	*/
	OldPassword string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewChangeCurrentUserPasswordParams() beforehand.
func (o *ChangeCurrentUserPasswordParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := r.ParseMultipartForm(32 << 20); err != nil {
		if err != http.ErrNotMultipart {
			return errors.New(400, "%v", err)
		} else if err := r.ParseForm(); err != nil {
			return errors.New(400, "%v", err)
		}
	}
	fds := runtime.Values(r.Form)

	fdNewPassword, fdhkNewPassword, _ := fds.GetOK("new_password")
	if err := o.bindNewPassword(fdNewPassword, fdhkNewPassword, route.Formats); err != nil {
		res = append(res, err)
	}

	fdOldPassword, fdhkOldPassword, _ := fds.GetOK("old_password")
	if err := o.bindOldPassword(fdOldPassword, fdhkOldPassword, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindNewPassword binds and validates parameter NewPassword from formData.
func (o *ChangeCurrentUserPasswordParams) bindNewPassword(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("new_password", "formData", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("new_password", "formData", raw); err != nil {
		return err
	}

	o.NewPassword = raw

	return nil
}

// bindOldPassword binds and validates parameter OldPassword from formData.
func (o *ChangeCurrentUserPasswordParams) bindOldPassword(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("old_password", "formData", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("old_password", "formData", raw); err != nil {
		return err
	}

	o.OldPassword = raw

	return nil
}
