// Code generated by go-swagger; DO NOT EDIT.

package analysis

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	v1 "swagger/apiserver/v1"
)

// AggregateOKCode is the HTTP code returned for type AggregateOK
const AggregateOKCode int = 200

/*AggregateOK A successful response.

swagger:response aggregateOK
*/
type AggregateOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Values `json:"body,omitempty"`
}

// NewAggregateOK creates AggregateOK with default headers values
func NewAggregateOK() *AggregateOK {

	return &AggregateOK{}
}

// WithPayload adds the payload to the aggregate o k response
func (o *AggregateOK) WithPayload(payload *v1.Values) *AggregateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the aggregate o k response
func (o *AggregateOK) SetPayload(payload *v1.Values) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AggregateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
