// Code generated by go-swagger; DO NOT EDIT.

package analysis

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AggregateHandlerFunc turns a function with the right signature into a aggregate handler
type AggregateHandlerFunc func(AggregateParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn AggregateHandlerFunc) Handle(params AggregateParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// AggregateHandler interface for that can handle valid aggregate params
type AggregateHandler interface {
	Handle(AggregateParams, interface{}) middleware.Responder
}

// NewAggregate creates a new http.Handler for the aggregate operation
func NewAggregate(ctx *middleware.Context, handler AggregateHandler) *Aggregate {
	return &Aggregate{Context: ctx, Handler: handler}
}

/*Aggregate swagger:route GET /v1/analysis/aggregate/{operation} analysis aggregate

数据统计

数据统计

*/
type Aggregate struct {
	Context *middleware.Context
	Handler AggregateHandler
}

func (o *Aggregate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAggregateParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
