// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeviceFieldInfos 属性定义列表
//
// swagger:model DeviceFieldInfos
type DeviceFieldInfos struct {

	// 属性定义列表
	DeviceFieldInfos []*DeviceFieldInfo `json:"deviceFieldInfos"`
}

// Validate validates this device field infos
func (m *DeviceFieldInfos) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeviceFieldInfos(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeviceFieldInfos) validateDeviceFieldInfos(formats strfmt.Registry) error {

	if swag.IsZero(m.DeviceFieldInfos) { // not required
		return nil
	}

	for i := 0; i < len(m.DeviceFieldInfos); i++ {
		if swag.IsZero(m.DeviceFieldInfos[i]) { // not required
			continue
		}

		if m.DeviceFieldInfos[i] != nil {
			if err := m.DeviceFieldInfos[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deviceFieldInfos" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeviceFieldInfos) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceFieldInfos) UnmarshalBinary(b []byte) error {
	var res DeviceFieldInfos
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
