// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeviceChartInfo 设备属性值列表
//
// swagger:model DeviceChartInfo
type DeviceChartInfo struct {

	// 创建时间(timestamp)
	Time int64 `json:"time"`

	// 设备属性值
	Value string `json:"value"`
}

// Validate validates this device chart info
func (m *DeviceChartInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeviceChartInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceChartInfo) UnmarshalBinary(b []byte) error {
	var res DeviceChartInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
