// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeviceTemplates 设备模版列表
//
// swagger:model DeviceTemplates
type DeviceTemplates struct {

	// 参数列表
	DeviceTemplates []*DeviceTemplate `json:"deviceTemplates"`

	// 设备属性值列表总数
	// Required: true
	TotalCount *int64 `json:"total_count"`
}

// Validate validates this device templates
func (m *DeviceTemplates) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeviceTemplates(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalCount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeviceTemplates) validateDeviceTemplates(formats strfmt.Registry) error {

	if swag.IsZero(m.DeviceTemplates) { // not required
		return nil
	}

	for i := 0; i < len(m.DeviceTemplates); i++ {
		if swag.IsZero(m.DeviceTemplates[i]) { // not required
			continue
		}

		if m.DeviceTemplates[i] != nil {
			if err := m.DeviceTemplates[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deviceTemplates" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *DeviceTemplates) validateTotalCount(formats strfmt.Registry) error {

	if err := validate.Required("total_count", "body", m.TotalCount); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeviceTemplates) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceTemplates) UnmarshalBinary(b []byte) error {
	var res DeviceTemplates
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
