// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeviceTemplate 设备模版信息
//
// swagger:model DeviceTemplate
type DeviceTemplate struct {

	// 设备类型名称
	// Required: true
	DeviceProfile *string `json:"deviceProfile"`

	// 属性信息列表
	FieldInfos []*FieldInfo `json:"fieldInfos"`

	// 设备类型展示名称
	// Required: true
	ProfileName *string `json:"profileName"`

	// 模版ID
	// Required: true
	UUID *string `json:"uuid"`
}

// Validate validates this device template
func (m *DeviceTemplate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeviceProfile(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFieldInfos(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProfileName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUUID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeviceTemplate) validateDeviceProfile(formats strfmt.Registry) error {

	if err := validate.Required("deviceProfile", "body", m.DeviceProfile); err != nil {
		return err
	}

	return nil
}

func (m *DeviceTemplate) validateFieldInfos(formats strfmt.Registry) error {

	if swag.IsZero(m.FieldInfos) { // not required
		return nil
	}

	for i := 0; i < len(m.FieldInfos); i++ {
		if swag.IsZero(m.FieldInfos[i]) { // not required
			continue
		}

		if m.FieldInfos[i] != nil {
			if err := m.FieldInfos[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("fieldInfos" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *DeviceTemplate) validateProfileName(formats strfmt.Registry) error {

	if err := validate.Required("profileName", "body", m.ProfileName); err != nil {
		return err
	}

	return nil
}

func (m *DeviceTemplate) validateUUID(formats strfmt.Registry) error {

	if err := validate.Required("uuid", "body", m.UUID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeviceTemplate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceTemplate) UnmarshalBinary(b []byte) error {
	var res DeviceTemplate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
