// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EarlyAlarmConfig 设备超限告警配置
//
// swagger:model EarlyAlarmConfig
type EarlyAlarmConfig struct {

	// 数值周期
	Cycle int64 `json:"cycle"`

	// 设备名称
	DeviceType string `json:"deviceType"`

	// 属性超限配置列表
	FieldLimits []*EarlyAlarmFieldLimit `json:"fieldLimits"`

	// 配置ID
	UUID string `json:"uuid"`
}

// Validate validates this early alarm config
func (m *EarlyAlarmConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFieldLimits(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EarlyAlarmConfig) validateFieldLimits(formats strfmt.Registry) error {

	if swag.IsZero(m.FieldLimits) { // not required
		return nil
	}

	for i := 0; i < len(m.FieldLimits); i++ {
		if swag.IsZero(m.FieldLimits[i]) { // not required
			continue
		}

		if m.FieldLimits[i] != nil {
			if err := m.FieldLimits[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("fieldLimits" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *EarlyAlarmConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EarlyAlarmConfig) UnmarshalBinary(b []byte) error {
	var res EarlyAlarmConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
