// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EarlyAlarmFieldLimit 属性超限配置
//
// swagger:model EarlyAlarmFieldLimit
type EarlyAlarmFieldLimit struct {

	// 属性名称
	FieldName string `json:"fieldName"`

	// 上限
	MaxLimit string `json:"maxLimit"`

	// 下限
	MinLimit string `json:"minLimit"`
}

// Validate validates this early alarm field limit
func (m *EarlyAlarmFieldLimit) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EarlyAlarmFieldLimit) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EarlyAlarmFieldLimit) UnmarshalBinary(b []byte) error {
	var res EarlyAlarmFieldLimit
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
