// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FieldTransfer 传输告警属性配置
//
// swagger:model FieldTransfer
type FieldTransfer struct {

	// 持续周期
	Duration int64 `json:"duration"`

	// 属性名称
	FieldName string `json:"fieldName"`
}

// Validate validates this field transfer
func (m *FieldTransfer) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FieldTransfer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FieldTransfer) UnmarshalBinary(b []byte) error {
	var res FieldTransfer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
