// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LongitudinalValues 纵向比较数值信息
//
// swagger:model LongitudinalValues
type LongitudinalValues struct {

	// 设备类型(A项、B项、C项)
	// Required: true
	DeviceType *string `json:"deviceType"`

	// value items
	ValueItems *ValueItem `json:"valueItems,omitempty"`
}

// Validate validates this longitudinal values
func (m *LongitudinalValues) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeviceType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValueItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LongitudinalValues) validateDeviceType(formats strfmt.Registry) error {

	if err := validate.Required("deviceType", "body", m.DeviceType); err != nil {
		return err
	}

	return nil
}

func (m *LongitudinalValues) validateValueItems(formats strfmt.Registry) error {

	if swag.IsZero(m.ValueItems) { // not required
		return nil
	}

	if m.ValueItems != nil {
		if err := m.ValueItems.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("valueItems")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LongitudinalValues) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LongitudinalValues) UnmarshalBinary(b []byte) error {
	var res LongitudinalValues
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
