// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SimilarTestingDevices 同类检测设备名称列表
//
// swagger:model similarTestingDevices
type SimilarTestingDevices struct {

	// 当前选择的检测设备名称
	// Required: true
	CurrentTestingDevice *string `json:"currentTestingDevice"`

	// 基础设备信息
	SimilarTestingDevices []string `json:"similarTestingDevices"`
}

// Validate validates this similar testing devices
func (m *SimilarTestingDevices) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCurrentTestingDevice(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SimilarTestingDevices) validateCurrentTestingDevice(formats strfmt.Registry) error {

	if err := validate.Required("currentTestingDevice", "body", m.CurrentTestingDevice); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SimilarTestingDevices) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SimilarTestingDevices) UnmarshalBinary(b []byte) error {
	var res SimilarTestingDevices
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
