// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Substation 变电站信息
//
// swagger:model Substation
type Substation struct {

	// 变电站名称
	// Required: true
	Name *string `json:"name"`

	// 检测设备信息
	TestingDevices []*TestingDevices `json:"testingDevices"`

	// 变电站ID
	// Required: true
	UUID *string `json:"uuid"`
}

// Validate validates this substation
func (m *Substation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTestingDevices(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUUID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Substation) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *Substation) validateTestingDevices(formats strfmt.Registry) error {

	if swag.IsZero(m.TestingDevices) { // not required
		return nil
	}

	for i := 0; i < len(m.TestingDevices); i++ {
		if swag.IsZero(m.TestingDevices[i]) { // not required
			continue
		}

		if m.TestingDevices[i] != nil {
			if err := m.TestingDevices[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("testingDevices" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Substation) validateUUID(formats strfmt.Registry) error {

	if err := validate.Required("uuid", "body", m.UUID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Substation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Substation) UnmarshalBinary(b []byte) error {
	var res Substation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
