// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Substations 变电站列表
//
// swagger:model Substations
type Substations struct {

	// 变电站列表
	Substations []*Substation `json:"substations"`
}

// Validate validates this substations
func (m *Substations) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubstations(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Substations) validateSubstations(formats strfmt.Registry) error {

	if swag.IsZero(m.Substations) { // not required
		return nil
	}

	for i := 0; i < len(m.Substations); i++ {
		if swag.IsZero(m.Substations[i]) { // not required
			continue
		}

		if m.Substations[i] != nil {
			if err := m.Substations[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("substations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Substations) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Substations) UnmarshalBinary(b []byte) error {
	var res Substations
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
