// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UploadDeviceInfo 上传设备信息
//
// swagger:model UploadDeviceInfo
type UploadDeviceInfo struct {

	// 基础设备ID
	BasicsID string `json:"basicsId,omitempty"`

	// 设备名称
	BasicsName string `json:"basicsName,omitempty"`

	// 相位
	Phase string `json:"phase,omitempty"`

	// 变电站名称
	StationName string `json:"stationName,omitempty"`

	// 检测设备名称
	TestingName string `json:"testingName,omitempty"`

	// 是否区分相位
	ThreePhase string `json:"threePhase,omitempty"`
}

// Validate validates this upload device info
func (m *UploadDeviceInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UploadDeviceInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UploadDeviceInfo) UnmarshalBinary(b []byte) error {
	var res UploadDeviceInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
