// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ValueItem 属性值列表
//
// swagger:model ValueItem
type ValueItem struct {

	// 创建时间(timestamp)
	Times []int64 `json:"times"`

	// 数值列表
	Values []string `json:"values"`
}

// Validate validates this value item
func (m *ValueItem) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ValueItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ValueItem) UnmarshalBinary(b []byte) error {
	var res ValueItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
