// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CheckBasicsDevicePhaseOKCode is the HTTP code returned for type CheckBasicsDevicePhaseOK
const CheckBasicsDevicePhaseOKCode int = 200

/*CheckBasicsDevicePhaseOK A successful response.

swagger:response checkBasicsDevicePhaseOK
*/
type CheckBasicsDevicePhaseOK struct {

	/*
	  In: Body
	*/
	Payload *CheckBasicsDevicePhaseOKBody `json:"body,omitempty"`
}

// NewCheckBasicsDevicePhaseOK creates CheckBasicsDevicePhaseOK with default headers values
func NewCheckBasicsDevicePhaseOK() *CheckBasicsDevicePhaseOK {

	return &CheckBasicsDevicePhaseOK{}
}

// WithPayload adds the payload to the check basics device phase o k response
func (o *CheckBasicsDevicePhaseOK) WithPayload(payload *CheckBasicsDevicePhaseOKBody) *CheckBasicsDevicePhaseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the check basics device phase o k response
func (o *CheckBasicsDevicePhaseOK) SetPayload(payload *CheckBasicsDevicePhaseOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CheckBasicsDevicePhaseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
