// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// DeleteDeviceURL generates an URL for the delete device operation
type DeleteDeviceURL struct {
	BasicsName  *string
	DeviceLevel *int8
	StationName *string
	TestingName *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteDeviceURL) WithBasePath(bp string) *DeleteDeviceURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteDeviceURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *DeleteDeviceURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/v1/devices"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var basicsNameQ string
	if o.BasicsName != nil {
		basicsNameQ = *o.BasicsName
	}
	if basicsNameQ != "" {
		qs.Set("basicsName", basicsNameQ)
	}

	var deviceLevelQ string
	if o.DeviceLevel != nil {
		deviceLevelQ = swag.FormatInt8(*o.DeviceLevel)
	}
	if deviceLevelQ != "" {
		qs.Set("deviceLevel", deviceLevelQ)
	}

	var stationNameQ string
	if o.StationName != nil {
		stationNameQ = *o.StationName
	}
	if stationNameQ != "" {
		qs.Set("stationName", stationNameQ)
	}

	var testingNameQ string
	if o.TestingName != nil {
		testingNameQ = *o.TestingName
	}
	if testingNameQ != "" {
		qs.Set("testingName", testingNameQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *DeleteDeviceURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *DeleteDeviceURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *DeleteDeviceURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on DeleteDeviceURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on DeleteDeviceURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *DeleteDeviceURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
