// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteDeviceOKCode is the HTTP code returned for type DeleteDeviceOK
const DeleteDeviceOKCode int = 200

/*DeleteDeviceOK A successful response.

swagger:response deleteDeviceOK
*/
type DeleteDeviceOK struct {
}

// NewDeleteDeviceOK creates DeleteDeviceOK with default headers values
func NewDeleteDeviceOK() *DeleteDeviceOK {

	return &DeleteDeviceOK{}
}

// WriteResponse to the client
func (o *DeleteDeviceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
