// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetBasicsDevicesParams creates a new GetBasicsDevicesParams object
// no default values defined in spec.
func NewGetBasicsDevicesParams() GetBasicsDevicesParams {

	return GetBasicsDevicesParams{}
}

// GetBasicsDevicesParams contains all the bound params for the get basics devices operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetBasicsDevices
type GetBasicsDevicesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*变电站名称
	  In: query
	*/
	StationName *string
	/*主变设备名称
	  In: query
	*/
	TestingDeviceName *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetBasicsDevicesParams() beforehand.
func (o *GetBasicsDevicesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qStationName, qhkStationName, _ := qs.GetOK("stationName")
	if err := o.bindStationName(qStationName, qhkStationName, route.Formats); err != nil {
		res = append(res, err)
	}

	qTestingDeviceName, qhkTestingDeviceName, _ := qs.GetOK("testingDeviceName")
	if err := o.bindTestingDeviceName(qTestingDeviceName, qhkTestingDeviceName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindStationName binds and validates parameter StationName from query.
func (o *GetBasicsDevicesParams) bindStationName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.StationName = &raw

	return nil
}

// bindTestingDeviceName binds and validates parameter TestingDeviceName from query.
func (o *GetBasicsDevicesParams) bindTestingDeviceName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.TestingDeviceName = &raw

	return nil
}
