// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDevicesHandlerFunc turns a function with the right signature into a get devices handler
type GetDevicesHandlerFunc func(GetDevicesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDevicesHandlerFunc) Handle(params GetDevicesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetDevicesHandler interface for that can handle valid get devices params
type GetDevicesHandler interface {
	Handle(GetDevicesParams, interface{}) middleware.Responder
}

// NewGetDevices creates a new http.Handler for the get devices operation
func NewGetDevices(ctx *middleware.Context, handler GetDevicesHandler) *GetDevices {
	return &GetDevices{Context: ctx, Handler: handler}
}

/*GetDevices swagger:route GET /v1/devices device getDevices

获取设备

获取全部设备列表

*/
type GetDevices struct {
	Context *middleware.Context
	Handler GetDevicesHandler
}

func (o *GetDevices) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDevicesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
