// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
)

// GetBasicsDevicesURL generates an URL for the get basics devices operation
type GetBasicsDevicesURL struct {
	StationName       *string
	TestingDeviceName *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetBasicsDevicesURL) WithBasePath(bp string) *GetBasicsDevicesURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetBasicsDevicesURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetBasicsDevicesURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/v1/devices/basics"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var stationNameQ string
	if o.StationName != nil {
		stationNameQ = *o.StationName
	}
	if stationNameQ != "" {
		qs.Set("stationName", stationNameQ)
	}

	var testingDeviceNameQ string
	if o.TestingDeviceName != nil {
		testingDeviceNameQ = *o.TestingDeviceName
	}
	if testingDeviceNameQ != "" {
		qs.Set("testingDeviceName", testingDeviceNameQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetBasicsDevicesURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetBasicsDevicesURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetBasicsDevicesURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetBasicsDevicesURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetBasicsDevicesURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetBasicsDevicesURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
