// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	v1 "swagger/apiserver/v1"

	"github.com/go-openapi/runtime/middleware"
)

// GetBasicsDevicesHandlerFunc turns a function with the right signature into a get basics devices handler
type GetBasicsDevicesHandlerFunc func(GetBasicsDevicesParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBasicsDevicesHandlerFunc) Handle(params GetBasicsDevicesParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetBasicsDevicesHandler interface for that can handle valid get basics devices params
type GetBasicsDevicesHandler interface {
	Handle(GetBasicsDevicesParams, *v1.Principal) middleware.Responder
}

// NewGetBasicsDevices creates a new http.Handler for the get basics devices operation
func NewGetBasicsDevices(ctx *middleware.Context, handler GetBasicsDevicesHandler) *GetBasicsDevices {
	return &GetBasicsDevices{Context: ctx, Handler: handler}
}

/*GetBasicsDevices swagger:route GET /v1/devices/basics device getBasicsDevices

获取基础设备

获取某检测设备下的基础设备列表

*/
type GetBasicsDevices struct {
	Context *middleware.Context
	Handler GetBasicsDevicesHandler
}

func (o *GetBasicsDevices) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetBasicsDevicesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
