// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	v1 "swagger/apiserver/v1"
)

// GetBasicsDevicesOKCode is the HTTP code returned for type GetBasicsDevicesOK
const GetBasicsDevicesOKCode int = 200

/*GetBasicsDevicesOK A successful response.

swagger:response getBasicsDevicesOK
*/
type GetBasicsDevicesOK struct {

	/*
	  In: Body
	*/
	Payload *v1.TestingDevices `json:"body,omitempty"`
}

// NewGetBasicsDevicesOK creates GetBasicsDevicesOK with default headers values
func NewGetBasicsDevicesOK() *GetBasicsDevicesOK {

	return &GetBasicsDevicesOK{}
}

// WithPayload adds the payload to the get basics devices o k response
func (o *GetBasicsDevicesOK) WithPayload(payload *v1.TestingDevices) *GetBasicsDevicesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get basics devices o k response
func (o *GetBasicsDevicesOK) SetPayload(payload *v1.TestingDevices) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBasicsDevicesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
