// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSimilarTestingDevicesHandlerFunc turns a function with the right signature into a get similar testing devices handler
type GetSimilarTestingDevicesHandlerFunc func(GetSimilarTestingDevicesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSimilarTestingDevicesHandlerFunc) Handle(params GetSimilarTestingDevicesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetSimilarTestingDevicesHandler interface for that can handle valid get similar testing devices params
type GetSimilarTestingDevicesHandler interface {
	Handle(GetSimilarTestingDevicesParams, interface{}) middleware.Responder
}

// NewGetSimilarTestingDevices creates a new http.Handler for the get similar testing devices operation
func NewGetSimilarTestingDevices(ctx *middleware.Context, handler GetSimilarTestingDevicesHandler) *GetSimilarTestingDevices {
	return &GetSimilarTestingDevices{Context: ctx, Handler: handler}
}

/*GetSimilarTestingDevices swagger:route GET /v1/devices/testing/similar device getSimilarTestingDevices

获取同类检测设备名称列表

通过基础设备获取所归属的检测设备的同类检测设备名称列表

*/
type GetSimilarTestingDevices struct {
	Context *middleware.Context
	Handler GetSimilarTestingDevicesHandler
}

func (o *GetSimilarTestingDevices) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSimilarTestingDevicesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
