// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetSimilarTestingDevicesParams creates a new GetSimilarTestingDevicesParams object
// no default values defined in spec.
func NewGetSimilarTestingDevicesParams() GetSimilarTestingDevicesParams {

	return GetSimilarTestingDevicesParams{}
}

// GetSimilarTestingDevicesParams contains all the bound params for the get similar testing devices operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetSimilarTestingDevices
type GetSimilarTestingDevicesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*基础设备名称
	  In: query
	*/
	DeviceName *string
	/*基础设备类型
	  In: query
	*/
	DeviceProfile *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetSimilarTestingDevicesParams() beforehand.
func (o *GetSimilarTestingDevicesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qDeviceName, qhkDeviceName, _ := qs.GetOK("deviceName")
	if err := o.bindDeviceName(qDeviceName, qhkDeviceName, route.Formats); err != nil {
		res = append(res, err)
	}

	qDeviceProfile, qhkDeviceProfile, _ := qs.GetOK("deviceProfile")
	if err := o.bindDeviceProfile(qDeviceProfile, qhkDeviceProfile, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDeviceName binds and validates parameter DeviceName from query.
func (o *GetSimilarTestingDevicesParams) bindDeviceName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.DeviceName = &raw

	return nil
}

// bindDeviceProfile binds and validates parameter DeviceProfile from query.
func (o *GetSimilarTestingDevicesParams) bindDeviceProfile(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.DeviceProfile = &raw

	return nil
}
