// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateDeviceOKCode is the HTTP code returned for type UpdateDeviceOK
const UpdateDeviceOKCode int = 200

/*UpdateDeviceOK A successful response.

swagger:response updateDeviceOK
*/
type UpdateDeviceOK struct {
}

// NewUpdateDeviceOK creates UpdateDeviceOK with default headers values
func NewUpdateDeviceOK() *UpdateDeviceOK {

	return &UpdateDeviceOK{}
}

// WriteResponse to the client
func (o *UpdateDeviceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
