// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	v1 "swagger/apiserver/v1"
)

// GetDeviceChartsOKCode is the HTTP code returned for type GetDeviceChartsOK
const GetDeviceChartsOKCode int = 200

/*GetDeviceChartsOK A successful response.

swagger:response getDeviceChartsOK
*/
type GetDeviceChartsOK struct {

	/*
	  In: Body
	*/
	Payload *v1.DeviceChart `json:"body,omitempty"`
}

// NewGetDeviceChartsOK creates GetDeviceChartsOK with default headers values
func NewGetDeviceChartsOK() *GetDeviceChartsOK {

	return &GetDeviceChartsOK{}
}

// WithPayload adds the payload to the get device charts o k response
func (o *GetDeviceChartsOK) WithPayload(payload *v1.DeviceChart) *GetDeviceChartsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get device charts o k response
func (o *GetDeviceChartsOK) SetPayload(payload *v1.DeviceChart) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDeviceChartsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
