// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	v1 "swagger/apiserver/v1"
)

// GetDeviceValuesOKCode is the HTTP code returned for type GetDeviceValuesOK
const GetDeviceValuesOKCode int = 200

/*GetDeviceValuesOK A successful response.

swagger:response getDeviceValuesOK
*/
type GetDeviceValuesOK struct {

	/*
	  In: Body
	*/
	Payload *v1.DeviceValues `json:"body,omitempty"`
}

// NewGetDeviceValuesOK creates GetDeviceValuesOK with default headers values
func NewGetDeviceValuesOK() *GetDeviceValuesOK {

	return &GetDeviceValuesOK{}
}

// WithPayload adds the payload to the get device values o k response
func (o *GetDeviceValuesOK) WithPayload(payload *v1.DeviceValues) *GetDeviceValuesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get device values o k response
func (o *GetDeviceValuesOK) SetPayload(payload *v1.DeviceValues) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDeviceValuesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
